version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:3000" # Map host:container
    container_name: react-app-container
    restart: always
